Bel automated returns
BenjaminTG/automatedreturns pull request #16
Opened 2020-07-13 03:44 UTC by bjones-brandcollective

2020-07-13 04:25 UTC, BenjaminTG commented
Hey @bjones-brandcollective I don't feel comfortable reviewing this sorry. Might need to escalate. :(

2020-07-13 05:05 UTC, dkerr-brandcollective requested changes

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/orderDetails.js
> +                  <p>1</p>
```suggestion
                  <p>{this.props.count}</p>
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/orderDetails.js
> +            <div>$1.00</div>
```suggestion
            <div>{this.props.amount}</div>
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/orderDetails.js
> +
I presume most (if not all) of this will be replaced by the `<RefundTotal />` and `<ExchangeTotal />` components?

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/orderDetails.js
> +        }
This is fine for now, but at the end you will probably want the state of the `OrderDetails` component to reflect the kind of data that is going to be sent to the server to submit the return request.

From [the documentation](https://docs.google.com/document/d/1xBk5xdV34KGzlhiBqPHqllHVhu7BIynAZUYEQXGgPyQ/edit#), that will end up looking something like this:

```json
"return_items": [
      {
          "level_code": "ABC_1234",
          "quantity": 1,
          "reason": "FAULTY",
          "photos": [
              "75801619-794b-477c-b495-2f268dfbcbfd",
              "79bda7e6-d829-4dfd-ae58-4e12a2856eaa",
              "a810570f-7497-4b15-8fc0-95e20b77cede"
          ],
          "comments": "The sole is missing from the shoe"
      }
  ]
```

As the customer manages their returns, the `return_items` object seen above can be updated to reflect the options that the customer selects.

You can then create a separate function (like `calculateQuantityToReturn()` and `calculateTotalRefund()`) which can be used to check the `return_items` object above, sum up the necessary values, and then send those amounts on to the `<ExchangeTotal />` and `<RefundTotal />` components as props.

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/orderItem.js
> +        var allowedQty = [this.props.item.quantity_return_allowed];
Should this be an array?

```suggestion
        var allowedQty = this.props.item.quantity_return_allowed;
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/orderItem.js
> +        this.props.returnExchangeDetails(choice)
Because this component is an order item component, redux probably shouldn't be used here.
The good news is that all you need to do is remove the mapping on `line 85`, and then this code will continue to work, as long as the `<OrderItem>` element has a prop called `returnExchangeDetails`.

In the `<OrderDetails />` component, you can update the `<OrderItem />` element to include the prop, and handle the update. For example:

```jsx
<OrderItem returnExchangeDetails={(data) => this.onOrderItemUpdated(data)} />
```

```js
class OrderItem {
    // ...
    function onOrderItemUpdated(data) {
        // Use `data` to update the state of the OrderItem component
    }
}
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/orderItem.js
> +export default connect(stateMappings, actionMappings)(OrderItem);
Redux should not be necessary for a component at a lower level (drop down, line item).

Anything that appears multiple times within the website *probably* shouldn't use redux directly. Redux is for application-level state -- that is to say, data that should be widely available in the application.

Changing the details of one line item should trigger a prop to run a function in a higher order component (e.g. order details). High order components can then link to redux to set application-level state, based on changes from lower order components like OrderItem, Dropdown, and Options.

All of this should be able to be swapped out for:
```suggestion
export default OrderItem;
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/components/submittedItem.js
> +                            <FlavorForm/>
`FlavorForm` needs to be replaced with appropriate component name, if it still needs to be here.

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/actionTypes.js
> +export const RETURN_EXCHANGE_DETAILS = "RETURN_EXCHANGE_DETAILS"
This is a good action to include.

It's helpful when actions have verbs in their name, so when we are viewing it in redux we understand what is happening, for what reason.

To that end, a minor suggested change:

```suggestion
export const UPDATE_RETURN_EXCHANGE_DETAILS = "UPDATE_RETURN_EXCHANGE_DETAILS"
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/actions.js
> +    RETURN_EXCHANGE_DETAILS,
```suggestion
    UPDATE_RETURN_EXCHANGE_DETAILS,
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/actions.js
> +    type: RETURN_EXCHANGE_DETAILS,
```suggestion
    type: UPDATE_RETURN_EXCHANGE_DETAILS,
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/actions.js
> +export const returnExchangeDetails = (quantityToReturn, quantityToExchange, keepRefundExchange, refundReason, exchangeReason, exchangeToSize, itemComments) => ({
Is this action to be run for each item, or for the entire return/exchange object?

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/reducers/belReducer.js
> +import { RETURN_EXCHANGE_DETAILS } from '../actionTypes'
```suggestion
import { UPDATE_RETURN_EXCHANGE_DETAILS } from '../actionTypes'
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/reducers/belReducer.js
> +            // return state;
Remove all of this please

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/reducers/belReducer.js
> +
Default reducer handler should return the existing state.

```suggestion
        default:
            return {...state}
```

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/reducers/index.js
> +import belReducer from './belReducer'
Please rename belReducer so that it relates to the function that it is performing.
If belReducer isn't being used any more, please remove this line.

2020-07-13 05:05 UTC, dkerr-brandcollective commented on src/store/reducers/index.js
> +    belReducer,
Please either rename or remove as per comment above

2020-07-14 01:08 UTC, bjones-brandcollective commented on src/components/orderDetails.js
> +
I thought to keep this grid here, as "Shipping will need to be paid for" will either always be there or a conditional component as well. As Total Refunded is constant, I thought about leaving that there as well - as it only changes IF they select a refund, but then "Exchanged quantity" only appears they select that option.

2020-07-14 01:13 UTC, bjones-brandcollective commented on src/components/orderDetails.js
> +        }
Okay - Quick Q - So we will bringing this information, then changing the state of it and updating it? I wasn't sure if this we'd want to modify the info directly or not.

2020-07-20 00:47 UTC, closed without merging